// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book_address.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	book_address.proto

It has these top-level messages:
	Person
	AddressBook
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name        string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id          int32                      `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email       string                     `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones      []*Person_PhoneNumber      `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
	LastUpdated *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetLastUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=main.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

// Our address book file is just one of these.
type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "main.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "main.AddressBook")
	proto.RegisterEnum("main.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AddressBookService service

type AddressBookServiceClient interface {
	GetAll(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*AddressBook, error)
}

type addressBookServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddressBookServiceClient(cc *grpc.ClientConn) AddressBookServiceClient {
	return &addressBookServiceClient{cc}
}

func (c *addressBookServiceClient) GetAll(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*AddressBook, error) {
	out := new(AddressBook)
	err := grpc.Invoke(ctx, "/main.AddressBookService/GetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddressBookService service

type AddressBookServiceServer interface {
	GetAll(context.Context, *google_protobuf1.Empty) (*AddressBook, error)
}

func RegisterAddressBookServiceServer(s *grpc.Server, srv AddressBookServiceServer) {
	s.RegisterService(&_AddressBookService_serviceDesc, srv)
}

func _AddressBookService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AddressBookService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).GetAll(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressBookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.AddressBookService",
	HandlerType: (*AddressBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _AddressBookService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book_address.proto",
}

func init() { proto.RegisterFile("book_address.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x6b, 0xa3, 0x50,
	0x10, 0xc7, 0xa3, 0x31, 0xb2, 0x19, 0x43, 0xc8, 0x0e, 0x4b, 0x10, 0xf7, 0xb0, 0x22, 0x7b, 0x90,
	0x5d, 0x30, 0x8b, 0x61, 0x8f, 0x7b, 0x48, 0x20, 0x6c, 0x4b, 0x9a, 0x26, 0xb5, 0x29, 0x3d, 0x06,
	0xad, 0xd3, 0x54, 0xa2, 0xbe, 0x87, 0xbe, 0x14, 0xf2, 0x77, 0xf5, 0x1f, 0x2c, 0xfa, 0x4c, 0x91,
	0xe6, 0x36, 0x3f, 0x3e, 0x33, 0xef, 0xfb, 0x7d, 0x03, 0x18, 0x31, 0x76, 0xd8, 0x85, 0x71, 0x5c,
	0x50, 0x59, 0x7a, 0xbc, 0x60, 0x82, 0xa1, 0x96, 0x85, 0x49, 0x6e, 0xfd, 0xd8, 0x33, 0xb6, 0x4f,
	0x69, 0x52, 0xd7, 0xa2, 0xe3, 0xf3, 0x44, 0x24, 0x19, 0x95, 0x22, 0xcc, 0xb8, 0xc4, 0xac, 0xef,
	0x9f, 0x01, 0xca, 0xb8, 0x38, 0xc9, 0xa6, 0xf3, 0xa6, 0x82, 0xbe, 0xa1, 0xa2, 0x64, 0x39, 0x22,
	0x68, 0x79, 0x98, 0x91, 0xa9, 0xd8, 0x8a, 0xdb, 0x0f, 0xea, 0x18, 0x87, 0xa0, 0x26, 0xb1, 0xa9,
	0xda, 0x8a, 0xdb, 0x0b, 0xd4, 0x24, 0xc6, 0x6f, 0xd0, 0xa3, 0x2c, 0x4c, 0x52, 0xb3, 0x5b, 0x43,
	0x32, 0xc1, 0x3f, 0xa0, 0xf3, 0x17, 0x96, 0x53, 0x69, 0x6a, 0x76, 0xd7, 0x35, 0x7c, 0xd3, 0xab,
	0x94, 0x79, 0x72, 0xaf, 0xb7, 0xa9, 0x5a, 0xb7, 0xc7, 0x2c, 0xa2, 0x22, 0x68, 0x38, 0xfc, 0x07,
	0x83, 0x34, 0x2c, 0xc5, 0xee, 0xc8, 0xe3, 0x50, 0x50, 0x6c, 0xf6, 0x6c, 0xc5, 0x35, 0x7c, 0xcb,
	0x93, 0x52, 0xbd, 0xb3, 0x54, 0x6f, 0x7b, 0xf6, 0x12, 0x18, 0x15, 0xff, 0x20, 0x71, 0xeb, 0x0e,
	0x8c, 0xd6, 0x56, 0x1c, 0x83, 0x9e, 0xd7, 0x51, 0xa3, 0xbd, 0xc9, 0xf0, 0x17, 0x68, 0xe2, 0xc4,
	0xa9, 0xd6, 0x3f, 0xf4, 0xc7, 0x97, 0xaa, 0xb6, 0x27, 0x4e, 0x41, 0xcd, 0x38, 0xbf, 0xa1, 0xff,
	0x51, 0x42, 0x00, 0x7d, 0xb5, 0x9e, 0x5f, 0xdf, 0x2c, 0x46, 0x1d, 0xfc, 0x02, 0xda, 0xd5, 0x7a,
	0xb5, 0x18, 0x29, 0x55, 0xf4, 0xb8, 0x0e, 0x96, 0x23, 0xd5, 0x99, 0x82, 0x31, 0x93, 0xa7, 0x98,
	0x33, 0x76, 0xc0, 0x9f, 0xa0, 0x73, 0x62, 0x3c, 0xad, 0xfe, 0xae, 0xf2, 0x3f, 0x68, 0xbf, 0x14,
	0x34, 0x3d, 0x7f, 0x09, 0xd8, 0x1a, 0xba, 0xa7, 0xe2, 0x35, 0x79, 0x22, 0xfc, 0x0b, 0xfa, 0x7f,
	0x12, 0xb3, 0x34, 0xc5, 0xf1, 0x85, 0xfb, 0x45, 0x75, 0x28, 0xeb, 0xab, 0xdc, 0xd6, 0x9a, 0x75,
	0x3a, 0x91, 0x5e, 0x43, 0xd3, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x94, 0xf4, 0x4c, 0x18,
	0x02, 0x00, 0x00,
}
